### ISSUE TITLE
Occurs when the model is loaded for the first time. orbit will not work

### ISSUE THREAD

**Issue by gonghaibo** [splinetool/react-spline#27] opened 2022-04-08 02:29 UTC
![image](https://user-images.githubusercontent.com/36252719/162351159-a5b96d68-33e1-45ea-9e02-86c727a2941f.png)
chrome 100
windows 11
react 17

**Comment by marcofugaro** [comment] 2022-04-08 07:19
Could you post your scene URL?

**Comment by marcofugaro** [comment] 2022-04-19 09:05
Could not reproduce, closing. Feel free to reopen when you have a reproducible example.

**Closed by marcofugaro** 2022-04-19 09:05 UTC
