### ISSUE TITLE
Access to spline URL is blocked by CORS

### ISSUE THREAD

**Issue by bhatvikrant** [splinetool/react-spline#44] opened 2022-06-05 20:42 UTC
<img width="1440" alt="Screenshot 2022-06-06 at 2 12 29 AM" src="https://user-images.githubusercontent.com/50735025/172069760-821801f1-bbd6-4d91-bd18-b522fee5725c.png">

visit the website at ~~https://useforest.vercel.app/~~ https://useforest-qpmt8vhgx-bhatvikrant.vercel.app/

**Comment by marcofugaro** [comment] 2022-06-06 08:28
Could you try again? The demo over at https://useforest.vercel.app/ doesn't error for me.

**Comment by bhatvikrant** [comment] 2022-06-06 09:04
Hey yes, I actually embedded the iframe for now. 
Test on this preview URL -> https://useforest-qpmt8vhgx-bhatvikrant.vercel.app/

**Comment by marcofugaro** [comment] 2022-06-06 09:20
Ok. I see the scene correctly, you sure it's not your network?

<img width="543" alt="image" src="https://user-images.githubusercontent.com/7217420/172133344-4eb4f00b-fa64-477f-ad4b-e5ae941542f8.png">

**Comment by bhatvikrant** [comment] 2022-06-06 09:54
This is how it looks for me. I don't think its my network
<img width="1512" alt="Screenshot 2022-06-06 at 3 24 21 PM" src="https://user-images.githubusercontent.com/50735025/172138877-f55b9ef0-0e5a-4c34-bb55-42f42f12a536.png">

**Comment by marcofugaro** [comment] 2022-06-06 13:13
Could you copy your request as cURL? I can't reproduce.

<img width="643" alt="image" src="https://user-images.githubusercontent.com/7217420/172167542-f98d9633-bbc2-426f-bccf-006716908be9.png">

**Comment by bhatvikrant** [comment] 2022-06-07 14:05
Hey @marcofugaro ?

**Comment by marcofugaro** [comment] 2022-06-14 07:30
Closing as we can't reproduce.

**Closed by marcofugaro** 2022-06-14 07:30 UTC
